# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db56f21d8af984f5b152e87ae1676a2a08759cc91cf1646abd16fca7210def394b0585b8e533ce33d89828c17a88af3d43602f1e2f6d47b5abce95cc8c714825

test:
  secret_key_base: 169a38b463e67502b2872068fa6eb19bea0f5fe411dcd07b0aa74ac81b6d1c3ecf3f19fb507db783eb145c7e5504cde25a7fe6d1d470a29d0d5a575589da6ea8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
